In [79]:
import matplotlib.pyplot as plt
import pandas as pd

import joblib

import warnings
warnings.filterwarnings("ignore")

from os.path import join
import sys

In [44]:
DATAFOLDER = join('..', 'data')
DATAFOLDER_RAW = join(DATAFOLDER, 'raw')

# Load Data

In [45]:
DATA_CURRENT_RAW_FOLDER = join(DATAFOLDER_RAW, 'Current')
DATA_CURRENT_RAW_FOLDER

'../data/raw/Current'

In [46]:
import glob
glob.glob(DATA_CURRENT_RAW_FOLDER + '/*')

['../data/raw/Current/v000_NORMAL_FR6000_FG5955_L000_0,5IN_SENSORC.csv',
 '../data/raw/Current/v000_FAULT_SC_HI_LVL2_FR4500_FG4387_L000_0,9IN_SENSORC.csv',
 '../data/raw/Current/v000_FAULT_SC_LI_LVL3_FR6000_FG5923_L000_0,4IN_SENSORC.csv',
 '../data/raw/Current/v000_FAULT_SC_LI_LVL3_FR4500_FG4403_L000_0,5IN_SENSORC.csv',
 '../data/raw/Current/v000_NORMAL_FR4500_FG4421_L000_0,7IN_SENSORC.csv',
 '../data/raw/Current/v000_FAULT_SC_HI_LVL2_FR6000_FG5942_L000_0,6IN_SENSORC.csv']

In [47]:
DATA_TO_READ = join(DATA_CURRENT_RAW_FOLDER, 'v000_NORMAL_FR6000_FG5955_L000_0,5IN_SENSORC.csv')

In [51]:
data_raw_normal = pd.read_csv(DATA_TO_READ)
data_raw_normal.head()

Current_R  Current_S  Current_T  Current_hall_R  Current_hall_S  \
0   0.035657  -1.402470   1.414564        2.713690        2.394956   
1  -0.104310  -1.389744   1.478187        2.695843        2.109424   
2  -0.218827  -1.338842   1.618156        2.698393        2.349067   
3  -0.295173  -1.224312   1.579983        2.685645        2.422999   
4  -0.486036  -1.275214   1.809024        2.670347        2.305727   

   Current_hall_T  Freq_Rated  Freq_Gen  CC_bus  Power  Load   I_R_rms  \
0        2.550505          60     59.55     210    0.1     0  1.184284   
1        2.547956          60     59.55     210    0.1     0  1.184284   
2        2.578549          60     59.55     210    0.1     0  1.184284   
3        2.573450          60     59.55     210    0.1     0  1.184284   
4        2.604043          60     59.55     210    0.1     0  1.184284   

    I_S_rms   I_T_rms  
0  1.188929  1.197345  
1  1.188929  1.197345  
2  1.188929  1.197345  
3  1.188929  1.197345  
4  1.188929  1.197345

In [53]:
type(data_raw_normal)

pandas.core.frame.DataFrame

In [54]:
data_raw_normal.describe()

Current_R     Current_S     Current_T  Current_hall_R  \
count  50000.000000  50000.000000  50000.000000    50000.000000   
mean      -0.010286      0.012611      0.002357        2.499768   
std        1.184251      1.188874      1.197354        0.135501   
min       -2.610977     -3.031342     -3.497098        0.299238   
25%       -1.185867     -1.173410     -1.181236        2.389894   
50%       -0.015240     -0.002658      0.002143        2.502075   
75%        1.180835      1.206271      1.198247        2.611707   
max        3.140361      3.229635      3.654078        3.236354   

       Current_hall_S  Current_hall_T  Freq_Rated      Freq_Gen   CC_bus  \
count    50000.000000    50000.000000     50000.0  5.000000e+04  50000.0   
mean         2.496935        2.491380        60.0  5.955000e+01    210.0   
std          0.135031        0.125434         0.0  2.842199e-14      0.0   
min         -0.083057        0.230558        60.0  5.955000e+01    210.0   
25%          2.382209        2.379696        60.0  5.955000e+01    210.0   
50%          2.499481        2.491869        60.0  5.955000e+01    210.0   
75%          2.614204        2.604043        60.0  5.955000e+01    210.0   
max          3.305090        3.284730        60.0  5.955000e+01    210.0   

              Power     Load       I_R_rms       I_S_rms       I_T_rms  
count  5.000000e+04  50000.0  5.000000e+04  50000.000000  5.000000e+04  
mean   1.000000e-01      0.0  1.184284e+00      1.188929  1.197345e+00  
std    1.387793e-17      0.0  4.440937e-16      0.000000  2.220468e-16  
min    1.000000e-01      0.0  1.184284e+00      1.188929  1.197345e+00  
25%    1.000000e-01      0.0  1.184284e+00      1.188929  1.197345e+00  
50%    1.000000e-01      0.0  1.184284e+00      1.188929  1.197345e+00  
75%    1.000000e-01      0.0  1.184284e+00      1.188929  1.197345e+00  
max    1.000000e-01      0.0  1.184284e+00      1.188929  1.197345e+00

In [55]:
data_raw_normal.hist()

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7fe3edae2400>,
      dtype=object)

### All currents

In [56]:
%matplotlib tk
plt.plot(data_raw_normal['Current_R'])
plt.plot(data_raw_normal['Current_S'])
plt.plot(data_raw_normal['Current_T'])

plt.legend(['R', 'S', 'T'])

plt.show()

### Normal **vs** Most critical Fault

In [9]:
DATA_TO_READ = join(DATA_CURRENT_RAW_FOLDER, 'v000_FAULT_SC_LI_LVL3_FR6000_FG5923_L000_0,4IN_SENSORC.csv')
data_raw_fault = pd.read_csv(DATA_TO_READ)

In [57]:
%matplotlib tk
plt.plot(data_raw_normal['Current_R'])
plt.plot(data_raw_fault['Current_R'])

plt.legend(['R-Normal', 'R-Fault'])

plt.show()

### Normal **vs** Least critical Fault

In [58]:
DATA_TO_READ = join(DATA_CURRENT_RAW_FOLDER, 'v000_FAULT_SC_HI_LVL2_FR6000_FG5942_L000_0,6IN_SENSORC.csv')
data_raw_fault_least = pd.read_csv(DATA_TO_READ)

In [64]:
%matplotlib tk
plt.plot(data_raw_normal['Current_R'])
plt.plot(data_raw_fault_least['Current_R'])

plt.legend(['R-Normal', 'R-Fault'])

plt.show()

# Create pipelines

In [14]:
from sklearn.pipeline import Pipeline, FeatureUnion
sys.path.append('../src')
from transforms import *

In [15]:
MODELS_FOLDER = join('..', 'models')
SELECTOR_FOLDER = join(MODELS_FOLDER, 'selector')
SCALER_FOLDER = join(MODELS_FOLDER, 'scaler')

In [128]:
data_extracted = pd.read_csv(join(DATA_FOLDER, 'v000_SCIG_SC_SENSORC_FOURIER.csv'))
data_extracted.head()

idx  fx1_R   fx0d5_R   fx1d5_R   fx2d5_R     fx3_R     fx5_R     fx7_R  \
0    1    1.0  0.007299  0.006626  0.000968  0.023378  0.023553  0.006339   
1    2    1.0  0.003416  0.006184  0.001155  0.023907  0.013409  0.005977   
2    3    1.0  0.003490  0.004380  0.000786  0.018111  0.011143  0.005009   
3    4    1.0  0.002984  0.002304  0.000533  0.019345  0.014027  0.004023   
4    5    1.0  0.004993  0.004015  0.001150  0.025392  0.018566  0.004693   

   fx1_S   fx0d5_S  ...     fx7_T  Freq_Rated  Freq_Gen  CC_bus  Power  \
0    1.0  0.007219  ...  0.006059        45.0     43.85     369   0.57   
1    1.0  0.003368  ...  0.005722        45.0     43.87     368   0.55   
2    1.0  0.003484  ...  0.004889        45.0     43.89     367   0.55   
3    1.0  0.002979  ...  0.003913        45.0     43.91     365   0.53   
4    1.0  0.004956  ...  0.004557        45.0     43.93     363   0.52   

    I_R_rms   I_S_rms   I_T_rms  Load  Class  
0  2.906343  2.920356  2.986445     0      1  
1  2.885150  2.896358  2.962763     0      1  
2  2.851384  2.863890  2.935414     0      1  
3  2.819084  2.827510  2.900116     0      1  
4  2.761420  2.774290  2.844834     0      1  

[5 rows x 31 columns]

In [129]:
FEATURES = ['fx0d5_R', 'fx1d5_R', 'fx2d5_R', 'fx3_R', 'fx5_R', 'fx7_R']

In [155]:
data_selected = data_extracted[FEATURES]
data_selected.head()

fx0d5_R   fx1d5_R   fx2d5_R     fx3_R     fx5_R     fx7_R
0  0.007299  0.006626  0.000968  0.023378  0.023553  0.006339
1  0.003416  0.006184  0.001155  0.023907  0.013409  0.005977
2  0.003490  0.004380  0.000786  0.018111  0.011143  0.005009
3  0.002984  0.002304  0.000533  0.019345  0.014027  0.004023
4  0.004993  0.004015  0.001150  0.025392  0.018566  0.004693

In [156]:
data_selected.shape

(1356, 6)

In [157]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [158]:
full_pipeline = Pipeline(
        [
            ('scaler', scaler),
        ]
    )

In [164]:
X = full_pipeline.fit_transform(data_selected.values)
y = data_extracted['Class']
print(X[0,:])

[-0.48480222 -0.32686418 -1.15543388 -0.89916022 -1.04780743 -1.55640884]


### Train classifier 

In [135]:
from sklearn.neural_network import MLPClassifier

In [136]:
clf_mlp = MLPClassifier()

In [137]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=2, shuffle=True)

In [138]:
for train_index, test_index in skf.split(X, y):
    X_train = X[train_index]
    X_test = X[test_index]
    y_train = y[train_index]
    y_test = y[test_index]
    
    clf_mlp.fit(X_train, y_train)

In [139]:
y_hat = clf_mlp.predict(X_test)

## Calculate metrics

In [140]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix

In [141]:
accuracy_score(y_test, y_hat)*100

60.946745562130175

In [142]:
confusion_matrix(y_test, y_hat)

array([[121,   1,   1,   0,   0,   1,   0],
       [  2,  31,  13,  14,  22,  19,   0],
       [  0,  16,  32,  23,  10,   7,   1],
       [  0,   8,  12,  65,   0,   6,   0],
       [  1,  21,  16,  14,  20,  13,   3],
       [  0,  10,   6,  10,   1,  71,   6],
       [  0,   0,   0,   0,   0,   7,  72]])

# How to deploy???

In [143]:
sys.path.append('..src/feature_extraction')

In [95]:
from feature_extraction.feature_extraction import Fourier, HOS

In [196]:
tf_fourier = Fourier(fs=5000.0, harmonics=(0.5, 1, 1.5, 2.5, 3, 5, 7), fundamental=60, window=10)

In [197]:
# plt.plot(data_raw_normal['Current_R'])

In [198]:
tf_fourier.transform(data_raw_normal['Current_R'])

{'fft': array([0.01720034, 0.0021591 , 0.00358161, ..., 0.00281298, 0.00057278,
        0.00353829]),
 'frequency': array([0.00000000e+00, 1.00004000e-01, 2.00008000e-01, ...,
        2.49979999e+03, 2.49990000e+03, 2.50000000e+03]),
 'features': [0.002133442562913511,
  0.005440678359628316,
  0.0036462996396356066,
  0.0030286058494310097,
  0.0032869067603151798,
  0.003966425845476924,
  0.004169981105669104],
 'features_vector': [0.5000200008000321,
  1.0000400016000641,
  1.6000640025601023,
  2.700108004320173,
  3.2001280051202046,
  5.400216008640346,
  7.6003040121604855]}

In [199]:
HOS().transform(data_raw_normal['Current_R'])

{'rms': 1.7294229225828563,
 'variance': 2.9908894999907614,
 'skewness': -0.0020636243361441217,
 'kurtosis': -1.4783552811506835,
 'features': [1.7294229225828563,
  2.9908894999907614,
  -0.0020636243361441217,
  -1.4783552811506835]}

# Montar o sistema real

Carregar dado

In [221]:
DATA_TO_READ = join(DATA_CURRENT_RAW_FOLDER, 'v000_NORMAL_FR6000_FG5955_L000_0,5IN_SENSORC.csv')
# DATA_TO_READ = join(DATA_CURRENT_RAW_FOLDER, 'v000_FAULT_SC_LI_LVL3_FR6000_FG5923_L000_0,4IN_SENSORC.csv')

In [222]:
data_raw_normal = pd.read_csv(DATA_TO_READ)

Extrair atributo

In [223]:
import numpy as np
x_feature = np.array(tf_fourier.transform(data_raw_normal['Current_R'])['features'])
x_feature

array([0.00196223, 0.00299272, 0.00265553, 0.00344627, 0.00296197,
       0.00350715, 0.00320512])

In [224]:
x_feature = x_feature/x_feature[1]
x_feature

array([0.65566815, 1.        , 0.88733028, 1.15155087, 0.98972416,
       1.17189389, 1.07097263])

In [225]:
x_feature = np.delete(x_feature, 1)
x_feature

array([0.65566815, 0.88733028, 1.15155087, 0.98972416, 1.17189389,
       1.07097263])

In [226]:
x_feature = x_feature.reshape((1,-1))
x_feature

array([[0.65566815, 0.88733028, 1.15155087, 0.98972416, 1.17189389,
        1.07097263]])

Normalização

In [227]:
x_std = scaler.transform(x_feature)
x_std

array([[105.57993294, 207.29405919, 762.27322753,  27.46048417,
         61.40859379, 150.19768072]])

In [228]:
clf_mlp.predict(x_std)

array([7])

In [ ]:
full_pippeline = FeatureUnion(
        [
            ('features_sf1', pipe_01),
            ('features_sf2', pipe_02),
        ]
    )

In [ ]:
    pipe_01 = Pipeline(
        [
            ('selector_sf1', tf_fourier),
            ('scaler_sf1', scaler),
        ]
    )